//REQUEST TYPES
export const GET_ALL_TODO_REQUEST = "GET_ALL_TODO_REQUEST";
export const DELETE_ALL_TODO_REQUEST = "DELETE_ALL_TODO_REQUEST";
export const ADD_TODO_REQUEST = "ADD_TODO_REQUEST";
export const DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST";
export const EDIT_TODO_REQUEST = "EDIT_TODO_REQUEST";

//COMPLETION TYPES
export const GET_ALL_TODO_COMPLETE = "GET_ALL_TODO_COMPLETE";
export const DELETE_ALL_TODO_COMPLETE = "DELETE_ALL_TODO_COMPLETE";
export const ADD_TODO_COMPLETE = "ADD_TODO_COMPLETE";
export const DELETE_TODO_COMPLETE = "DELETE_TODO_COMPLETE";
export const EDIT_TODO_COMPLETE = "EDIT_TODO_COMPLETE";

//FAILURE TYPES
export const GET_ALL_TODO_FAILURE = "GET_ALL_TODO_FAILURE";
export const DELETE_ALL_TODO_FAILURE = "DELETE_ALL_TODO_FAILURE";
export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE";
export const DELETE_TODO_FAILURE = "DELETE_TODO_FAILURE";
export const EDIT_TODO_FAILURE = "EDIT_TODO_FAILURE";

// {EDIT_TODO_FAILURE,DELETE_TODO_FAILURE,ADD_TODO_FAILURE,DELETE_ALL_TODO_FAILURE,GET_ALL_TODO_FAILURE,EDIT_TODO_COMPLETE,DELETE_TODO_COMPLETE,ADD_TODO_COMPLETE,DELETE_ALL_TODO_COMPLETE,GET_ALL_TODO_COMPLETE,EDIT_TODO_REQUEST,DELETE_TODO_REQUEST,ADD_TODO_REQUEST,DELETE_ALL_TODO_REQUEST,GET_ALL_TODO_REQUEST}

export const ADD_TO_BE_EDITED_TODO_REQUEST = "ADD_TO_BE_EDITED_TODO_REQUEST";
export const ADD_TO_BE_EDITED_TODO_COMPLETE = "ADD_TO_BE_EDITED_TODO_COMPLETE";

export const CLEAR_TO_BE_EDITED_REQUEST = "CLEAR_TO_BE_EDITED_REQUEST";
export const CLEAR_TO_BE_EDITED_COMPLETE = "CLEAR_TO_BE_EDITED_COMPLETE";

export const CLEAR_MESSAGE_REQUEST = "CLEAR_MESSAGE_REQUEST";
export const CLEAR_MESSAGE_COMPLETE = "CLEAR_MESSAGE_COMPLETE";
